### ISSUE TITLE
Update NPM Package with the new typescript file.

### ISSUE THREAD

**Issue by ilkovs** [christo-pr/dangerously-set-html-content-v1#13]
The TS file is missing when installing the package, which is causing it to not work.

**Comment by christo-pr** [comment]
@ilkovs  What version are you using? `v1.0.8` does have the TS definition file included

**Comment by ilkovs** [comment]
For some reason, the package is showing as missing when adding it to a component. Figured it was the TS file causing it. I have the   **"dangerously-set-html-content": "^1.0.8"**.

**Comment by christo-pr** [comment]
Hmmm weird, I just tried and everything was working fine. You could check on your `node_modules/`, you should have something like this: 
![image](https://user-images.githubusercontent.com/14341735/89543133-2d327780-d7c6-11ea-8269-850ce53c0190.png)

**Comment by ilkovs** [comment]
I have this but had to manually add the TS file. My concern is whether the package will work in prod vs. the way it works locally on my end.

<img width="218" alt="Screen Shot 2020-08-06 at 10 22 15 AM" src="https://user-images.githubusercontent.com/36686175/89543364-cfeef400-d7ce-11ea-8a44-e1d70563f976.png">

**Comment by christo-pr** [comment]
I don't think you need to manually add the file to the `dist/` folder, you shouldn't change anything on the `node_modules/` folder. Can you please post the actual error?.

Regarding to the prod vs local, I just tried using it with a `cra` example app and it didn't give any problem running the production build.

**Comment by ilkovs** [comment]
Just wiped it out and install it again, seems to work now. Not sure what was the reason behind not updating the package. Appreciate your help on the matter! Thanks

**Comment by christo-pr** [comment]
@ilkovs Great! Probably some weird npm cache, good to know that's working now!
