### ISSUE TITLE
Anchor don't work

### ISSUE THREAD

**Issue by greatwitenorth** [christo-pr/dangerously-set-html-content-v1#20]
When using React's dangerouslySetInnerHTML I'm able to create a div with an id and use an anchor tag elsewhere to jump to that point on the page. 

When I use this library as a replacement the anchor tags stop working. They do not jump down to the expected stop on the page anymore. 

Is this a current limitation of the library?

**Comment by christo-pr** [comment]
Do you have an environment where I can see that's not working, I just test it and seems to be working fine, not sure if I missed something on my test,  but this did the trick:

```
import React, { useState } from 'react'
import InnerHTML from 'dangerously-set-html-content'

export default function App() {

  const content = `
    <div style="background:green;height:500px"></div>
    <div style="background:red;height:500px"></div>
    <div style="background:blue;height:500px"></div>
    <div id="test" style="background:pink;height:500px"></div>
    <script>
      console.log('hacked!')
    </script>
  `

  return (
    <div>
      <a href="#test">testing</a>
      <InnerHTML style={{color: "white", background: "red"}} html={content} />
    </div>
  );
}
```

**Comment by sdhull** [comment]
I read this as a problem when `content` contains the `<a href="#test">test</a>` 👀

**Comment by christo-pr** [comment]
Closing this.

Using the example above, both scenarios work for me, having the `a` within the `content` or outside, it's jumping to the element
