### ISSUE TITLE
Self-Enclosing Div's seem to cause rendering issues

### ISSUE THREAD

**Issue by DeClaessens** [christo-pr/dangerously-set-html-content-v1#51]
Hi there!

I've been struggling with this issue using your package. I am however unsure if the issue is tied to your issue, or `dangerouslySetInnerHtml ` within React as a while.

The issue occurs when working with self-enclosing divs, possible other tags aswell. It seems to be unable to correctly render these, and interpret them in a different manner.

Example:

```
        <div class="container">
          <div class="1">
            <div class="1.1"/>
            <div class="1.2"/>
          </div>
          <div class="2">
            <div class="2.1"/>
            <div class="2.2"/>
          </div>
        </div>
```

Will render as

```
  <div class="container">
    <div class="1">
      <div class="1.1">
        <div class="1.2"></div>
        <div class="2">
          <div class="2.1">
            <div class="2.2"></div>
          </div>
        </div>
      </div>
    </div>
  </div>
```

**Comment by christo-pr** [comment]
HI @DeClaessens! Sorry for late response!

Well I'm pretty sure I'm not doing any fancy parsing of the content you passed.
One thing to mention, the string you passed in must be valid html code, not JSX. The `div` tag is a normal tag not a void tag (only void tags are able to be self-enclose), you can check the [HTML5 Spec](https://html.spec.whatwg.org/multipage/syntax.html#void-elements).

So I would suggest to just use normal divs
