### ISSUE TITLE
Does not render HTML on SSR pages

### ISSUE THREAD

**Issue by yashvekaria** [christo-pr/dangerously-set-html-content-v1#52]
Hi,

I am using Gatsby in the frontend and I had used this package in order to display article content which also had Instagram, Twitter embedded scripts codes. 

Here are the code snippet (I had added static text) 
![1](https://user-images.githubusercontent.com/5152954/143991103-4c8ae54b-1e0b-47e0-9966-efc700db2142.png)

Now on the gatsby build (SSR). I don't find any article content on checking that build pages or running that page by disabling JS from chrome dev tools. 

Here is the dom element snippet (JS disabled)
![2](https://user-images.githubusercontent.com/5152954/143991301-d8a0c3f6-74c2-4004-8a55-833f1bde8727.png)

**Comment by ownerni** [comment]
We also need this functionality of server side rendering, please help how to fix this bug ?

**Comment by christo-pr** [comment]
I'm really sorry about this, this feature is only meant to work on a client environment, so the normal behavior will be nothing in there while doing SSR.
