### ISSUE TITLE
Can not render Javascript code with "\" symbol

### ISSUE THREAD

**Issue by nhatcuongboy** [christo-pr/dangerously-set-html-content-v1#53]
When I insert symbol \ in my JS code, after render this symbol will disappear, so my code wrong. Please check it for me. Thanks

`const html = '
    <div>This wil be rendered</div>
    <script>
     var pattern = /^[+]?\d+(\.\d+)?$/;
      alert(pattern.test('123abc'))
    </script>'
`

**Comment by christo-pr** [comment]
I think you have a typo in your code, this seems to be working fine for me:

```js
import React from 'react'
import InnerHTML from 'dangerously-set-html-content'

export function App() {
  const html =
    "<div>This wil be rendered</div> <script> var pattern = /^[+]?d+(.d+)?$/; alert(pattern.test('123abc')) </script>"

  return (
    <div>
      <InnerHTML html={html} />
    </div>
  )
}
```

As you can see, I've replace the enclosed `'` with `"` so the this: `pattern.test('123abc')` can correctly get execute.

If you still having this problem, feel free to re-open this issue.

**Comment by nhatcuongboy** [comment]
Some pattern have different meanings. Ex: \B matches the empty string not at the beginning or end of a word
This requires me use symbol \

**Comment by christo-pr** [comment]
Yeah, that's not the issue, the problem is the single quotes (`'`) vs double qoutes(`"`), maybe you can try with the `Regex` constructor instead, but this lib doesn't do any type of formatting or cleaning to the value of the `html` prop
